#Ľubor Koka
version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: VAVJS
    ports:
      - '5432:5432'
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - 8080:8080